/*! Adapted from theaestheticslyrics, commit 499161944ce1af965398ce038073dcd890bf5f66. Copyright (c) 2026 darshanseenivasakumar. MIT; see ./LICENSE. */
/**
 * Word → icon for the Visual styles (about 800 words, like Verci's ~770).
 *   f:<name>  Fluent UI System Icon (MIT), tinted with the highlight colour
 *             — Microsoft's counterpart to Apple's SF Symbols.
 *   e:<char>  Colour emoji from Segoe UI Emoji.
 * Keys are base forms; resolve.ts also tries plural, -ing, -ed and -ly forms.
 * When a word appears in two groups, the first group wins.
 */
const GROUPS: ReadonlyArray<readonly [icon: string, words: string]> = [
    // Love and feelings
    [
        'f:heart',
        'love lover lovers beloved heart darling sweetheart valentine adore romance romantic passion affection crush babe baby honey sweetie forever',
    ],
    ['f:heart-broken', 'heartbreak heartbroken broken breakup shattered heartache'],
    ['e:😘', 'kiss smooch'],
    ['e:😊', 'smile happy happiness joy joyful glad delight cheerful'],
    ['e:😂', 'laugh laughter funny joke lol hilarious'],
    ['e:😍', 'beautiful gorgeous pretty lovely cute stunning'],
    ['e:😢', 'cry weep sob sobbing tearful'],
    ['e:😔', 'sad sadness sorrow unhappy lonely loneliness alone lonesome miserable misery regret'],
    ['e:😡', 'angry anger mad rage hate furious hatred'],
    ['e:😱', 'scared scary fear afraid terrified horror panic nightmare'],
    ['e:🥺', 'please beg sorry apologize'],
    ['e:🤔', 'wonder maybe perhaps question doubt curious'],
    ['e:😏', 'flirt tease wink'],
    ['e:🤯', 'crazy insane wild madness'],
    ['e:🥳', 'fun party celebrate celebration birthday'],
    ['e:😇', 'angel angels halo innocent'],
    ['e:😈', 'devil evil sin sinner wicked demon'],
    ['e:💀', 'dead death die dying kill killer skull grave funeral'],
    ['e:👻', 'ghost haunt haunted spooky'],
    ['e:🙏', 'pray prayer bless blessed blessing grateful thankful thank thanks grace'],
    ['e:🤞', 'hope hopeful wish luck lucky'],
    ['e:✌️', 'peace peaceful calm'],
    ['e:💪', 'strong strength muscle power powerful tough'],
    ['e:⚔️', 'fight battle war warrior enemy soldier army'],
    ['e:🗣️', 'shout scream yell loud'],
    ['e:😴', 'tired exhausted yawn'],
    ['e:🤡', 'clown fool foolish joker'],
    ['e:🤫', 'shh hush whisper'],
    ['e:😎', 'swag chill fresh'],

    // Eyes, body, people
    ['f:eye', 'eye see saw seen look watch stare gaze glance sight vision view witness notice'],
    ['f:eye-off', 'blind unseen invisible hidden hide'],
    ['f:hand-left', 'hand touch hold held grab reach palm grip'],
    ['f:hand-wave', 'hello hi hey goodbye bye farewell wave'],
    ['f:handshake', 'deal promise trust partner agreement'],
    ['f:thumb-like', 'yes okay ok good great fine nice cool'],
    ['f:thumb-dislike', 'bad worse worst wrong'],
    ['f:person', 'man boy guy stranger somebody someone anybody anyone nobody person gentleman'],
    [
        'f:people',
        'people crowd friend friendship everybody everyone together family squad crew gang neighbors',
    ],
    ['f:accessibility', 'human soul spirit'],
    ['f:brain', 'mind brain think thought remember memory smart genius wise'],
    ['f:heart-pulse', 'alive life living heartbeat pulse breath breathe breathless'],
    ['f:fingerprint', 'identity trace'],
    ['e:👄', 'lips mouth tongue'],
    ['e:👂', 'ear ears'],
    ['e:💇', 'hair'],
    ['e:🦶', 'feet foot barefoot'],
    ['e:👶', 'child children kid kids young youth newborn infant'],
    ['e:👩', 'woman women girl girls lady ladies'],
    ['e:🚶', 'walk step steps wander stroll'],
    ['e:💃', 'dance dancer dancefloor'],
    ['e:🩸', 'blood bleed wound'],
    ['e:🦴', 'bone bones'],

    // Night, sky and weather
    [
        'f:weather-moon',
        'moon moonlight lunar night tonight midnight nighttime evening dark darkness',
    ],
    [
        'f:weather-sunny',
        'sun sunny sunshine sunlight sunrise sunset summer day daylight morning dawn bright shine noon',
    ],
    ['f:star', 'star starry starlight twinkle famous fame superstar'],
    ['f:weather-rain', 'rain rainy downpour shower monsoon umbrella'],
    ['f:weather-thunderstorm', 'storm stormy thunder'],
    ['f:weather-snow', 'snow snowflake winter frozen freeze ice icy cold chill frost'],
    ['f:cloud', 'cloud sky skies heaven'],
    ['f:weather-fog', 'fog foggy mist misty haze hazy'],
    ['f:weather-cloudy', 'cloudy grey gray gloomy'],
    ['f:weather-drizzle', 'drizzle'],
    ['f:weather-partly-cloudy-day', 'weather forecast'],
    ['f:flash', 'lightning electric electricity energy shock flash'],
    ['e:🌈', 'rainbow'],
    ['e:🌪️', 'tornado hurricane whirlwind'],
    ['e:🌬️', 'wind breeze blow gust'],
    ['e:☄️', 'comet meteor'],
    ['e:🌅', 'horizon'],
    ['e:🎆', 'fireworks firework'],

    // Fire and water
    ['f:fire', 'fire burn flame blaze hot heat ignite inferno lit smoke ember spark'],
    ['f:water', 'water ocean sea tide river lake flood swim wet'],
    ['f:drop', 'tear tears teardrop drop drip'],
    ['e:🌊', 'surf splash'],
    ['e:🌋', 'volcano erupt lava'],

    // Places and travel
    ['f:home', 'home house household hometown roof'],
    ['f:building', 'building tower skyscraper office apartment hotel'],
    ['f:city', 'city town downtown street avenue boulevard neighborhood urban metropolis'],
    ['f:road', 'road highway freeway lane path route journey trip travel'],
    ['f:vehicle-car', 'car drive driver ride cruise taxi cab wheel engine speed'],
    ['f:airplane', 'plane airplane flight fly airport jet takeoff'],
    ['f:rocket', 'rocket launch space astronaut liftoff'],
    ['f:planet', 'planet galaxy universe cosmos cosmic orbit saturn mars venus'],
    ['f:earth', 'earth world globe global'],
    ['f:globe', 'international worldwide country nation'],
    ['f:map', 'map atlas'],
    ['f:location', 'place location somewhere anywhere nowhere destination address'],
    ['f:compass-northwest', 'north south east west direction lost compass'],
    ['f:mountain-trail', 'mountain hill climb peak valley summit'],
    ['f:vehicle-bicycle', 'bike bicycle cycle'],
    ['f:building-bank', 'bank vault'],
    ['f:door', 'door gate exit entrance enter'],
    ['f:window', 'window glass'],
    ['f:bed', 'bed pillow sheets bedroom mattress'],
    ['e:🏝️', 'island paradise beach shore coast'],
    ['e:🏖️', 'vacation holiday'],
    ['e:⛵', 'boat sail sailor ship harbor harbour'],
    ['e:⚓', 'anchor'],
    ['e:🚂', 'train railway'],
    ['e:🚌', 'bus'],
    ['e:🏍️', 'motorcycle motorbike'],
    ['e:🌉', 'bridge'],
    ['e:🧱', 'wall brick'],
    ['e:⛪', 'church chapel'],
    ['e:🏜️', 'desert dune'],
    ['e:🎡', 'ferris carnival fair'],
    ['e:🎢', 'rollercoaster'],
    ['e:🧳', 'suitcase luggage'],

    // Time
    ['f:clock', 'time clock hour minute second oclock late early moment'],
    ['f:hourglass', 'eternity eternal endless waiting wait patience'],
    ['f:calendar', 'date week weekend month year anniversary tomorrow yesterday today calendar'],
    ['f:clock-alarm', 'alarm wake woke awake'],

    // Talk, phone, music
    ['f:phone', 'phone cellphone mobile text message screen'],
    ['f:call', 'call ring dial hotline'],
    ['f:chat', 'talk say said speak spoke tell told conversation word chat'],
    ['f:mail', 'letter mail mailbox envelope postcard'],
    ['f:mic', 'sing sang singer song voice karaoke microphone mic'],
    [
        'f:music-note-2',
        'music melody tune rhythm beat harmony chorus verse lyric record radio playlist album',
    ],
    ['f:headphones', 'headphones listen hear heard'],
    ['f:speaker-2', 'sound noise volume bass'],
    ['f:speaker-mute', 'quiet silence silent mute'],
    ['f:guitar', 'guitar band rock strum'],
    ['f:video', 'movie film cinema tv television scene'],
    ['f:camera', 'camera photo picture photograph selfie pose'],
    ['e:🥁', 'drum drums drummer'],
    ['e:🎹', 'piano'],
    ['e:🎺', 'trumpet horn'],
    ['e:🎻', 'violin cello'],
    ['e:🪩', 'disco club'],

    // Light, magic, value
    ['f:lightbulb', 'idea light bulb glow'],
    ['f:flashlight', 'torch flashlight'],
    ['f:sparkle', 'magic magical sparkle glitter shiny shimmer miracle glory'],
    ['f:wand', 'spell wizard witch'],
    ['f:crown', 'king queen crown royal royalty prince princess throne kingdom empire'],
    ['f:diamond', 'diamond gem jewel precious bling'],
    ['f:money', 'money cash dollar paid pay rich wealth wealthy bill price rent'],
    ['f:wallet', 'wallet purse poor'],
    ['f:cart', 'shop shopping buy bought sell sold store market'],
    ['f:gift', 'gift present surprise'],
    ['f:trophy', 'win winning won winner champion trophy victory prize gold medal'],
    ['f:target', 'goal aim target focus'],
    ['f:shield', 'protect protection safe safety shield guard armor'],
    ['f:lock-closed', 'lock locked secret private prison jail cage trapped'],
    ['f:lock-open', 'free freedom release liberty unchain'],
    ['f:key', 'key unlock answer'],
    ['f:ribbon', 'award honor'],
    ['f:puzzle-piece', 'puzzle piece missing'],
    ['f:chess', 'chess strategy'],
    ['f:games', 'gamer gaming arcade'],
    ['f:alert', 'warning danger dangerous emergency siren'],
    ['f:gavel', 'judge judgment law justice court guilty'],
    ['f:scales', 'balance fair equal'],
    ['f:box', 'box package parcel'],
    ['f:service-bell', 'bell'],
    ['f:pulse', 'vibe vibes frequency'],
    ['e:💍', 'wedding marry married bride groom'],
    ['e:💐', 'bouquet'],
    ['e:🎲', 'dice gamble gambling chance'],
    ['e:🃏', 'card cards poker'],
    ['e:🎭', 'mask masks drama'],
    ['e:🕯️', 'candle candles'],
    ['e:🧸', 'teddy toy'],
    ['e:🪞', 'mirror reflection'],
    ['e:♾️', 'infinity infinite'],
    ['e:💯', 'real hundred percent'],
    ['e:🏁', 'finish finale'],
    ['e:⛓️', 'chain chains'],
    ['e:🔫', 'gun shoot shooting shot bullet trigger'],
    ['e:🗡️', 'knife blade sword'],
    ['e:💣', 'bomb explode explosion boom'],
    ['e:💊', 'pill medicine drug high'],

    // Words, art, learning
    ['f:book', 'book story page chapter novel read poem poetry'],
    ['f:pen', 'write wrote written pen pencil sign signature'],
    ['f:paint-brush', 'paint painting art artist canvas color colour'],
    ['f:video', 'show'],

    // Movement and play
    ['f:run', 'run ran runner race chase escape'],
    ['f:sport', 'game play ball team'],
    ['e:💨', 'fast faster quick quickly rush hurry'],
    ['f:animal-turtle', 'turtle slow'],

    // Sleep and dreams
    ['f:sleep', 'sleep slept asleep dream dreamer nap sleepy'],

    // Food and drink
    ['f:food', 'food eat ate hungry dinner lunch breakfast feast meal kitchen cook'],
    ['f:drink-wine', 'wine champagne toast cheers bottle'],
    ['f:drink-beer', 'beer bar drunk drink pub'],
    ['f:drink-coffee', 'coffee tea cafe caffeine cup mug'],
    ['f:food-cake', 'cake dessert'],
    ['f:food-apple', 'apple fruit'],
    ['f:food-pizza', 'pizza'],
    ['f:food-fish', 'fish fishing'],
    ['f:balloon', 'balloon festival'],
    ['f:ticket', 'ticket concert'],
    ['e:🍒', 'cherry cherries'],
    ['e:🍓', 'strawberry strawberries'],
    ['e:🍑', 'peach'],
    ['e:🍋', 'lemon lemonade'],
    ['e:🍫', 'chocolate'],
    ['e:🍬', 'candy sugar sweet'],
    ['e:🍦', 'icecream'],
    ['e:🍭', 'lollipop'],
    ['e:🍔', 'burger'],
    ['e:🍟', 'fries'],
    ['e:🌮', 'taco tacos'],
    ['e:🍜', 'noodles ramen'],
    ['e:🍣', 'sushi'],
    ['e:🍩', 'donut doughnut'],
    ['e:🍪', 'cookie'],
    ['e:🍞', 'bread'],
    ['e:🧀', 'cheese'],
    ['e:🥑', 'avocado'],
    ['e:🌶️', 'spicy pepper'],
    ['e:🥛', 'milk'],
    ['e:🧃', 'juice'],
    ['e:🍹', 'cocktail'],
    ['e:🍸', 'martini'],
    ['e:🍯', 'syrup'],
    ['e:🚬', 'cigarette'],

    // Nature
    ['f:leaf', 'leaf leaves green nature spring autumn garden grass'],
    ['f:tree-deciduous', 'tree forest woods jungle'],
    ['f:earth-leaf', 'environment planetary'],
    ['e:🌹', 'rose roses'],
    ['e:🌸', 'flower blossom bloom petal'],
    ['e:🥀', 'wilted withered'],
    ['e:🌻', 'sunflower'],
    ['e:🍀', 'clover'],
    ['e:🌾', 'field wheat'],
    ['e:🌵', 'cactus'],

    // Animals
    ['f:animal-cat', 'cat kitten kitty'],
    ['f:animal-dog', 'dog puppy'],
    ['f:animal-rabbit', 'rabbit bunny'],
    ['f:bug', 'bug insect'],
    ['e:🦋', 'butterfly butterflies'],
    ['e:🐦', 'bird wing wings feather'],
    ['e:🕊️', 'dove'],
    ['e:🦅', 'eagle hawk'],
    ['e:🐍', 'snake serpent'],
    ['e:🐺', 'wolf wolves'],
    ['e:🦁', 'lion'],
    ['e:🐯', 'tiger'],
    ['e:🐎', 'horse pony'],
    ['e:🐝', 'bee bees'],
    ['e:🐉', 'dragon'],
    ['e:🦄', 'unicorn'],
    ['e:🐻', 'bear'],
    ['e:🦊', 'fox'],
    ['e:🐒', 'monkey'],
    ['e:🦈', 'shark'],
    ['e:🐬', 'dolphin'],
    ['e:🐙', 'octopus'],
    ['e:🕷️', 'spider'],
    ['e:🦇', 'bat vampire'],
    ['e:🦉', 'owl'],
    ['e:🐑', 'sheep lamb'],
    ['e:🐷', 'pig'],
    ['e:🐄', 'cow'],

    // Fantasy and machines
    ['e:👽', 'alien aliens'],
    ['e:🤖', 'robot machine'],
    ['e:🧜', 'mermaid'],
    ['e:🧚', 'fairy'],
    ['e:🧟', 'zombie'],

    // Clothes and style
    ['e:🧥', 'coat jacket'],
    ['e:👗', 'dress'],
    ['e:👠', 'heels'],
    ['e:👟', 'shoes sneakers kicks'],
    ['f:glasses', 'glasses shades sunglasses'],
    ['e:👔', 'suit tie'],
    ['e:💄', 'lipstick makeup'],
    ['e:💅', 'nails manicure'],
    ['e:🧢', 'hat cap'],
];

function build(): Readonly<Record<string, string>> {
    const map: Record<string, string> = {};
    for (const [icon, words] of GROUPS) {
        for (const word of words.split(/\s+/)) {
            if (word && !(word in map)) map[word] = icon;
        }
    }
    return Object.freeze(map);
}

export const WORD_ICONS = build();
