/*! Adapted from theaestheticslyrics, commit 499161944ce1af965398ce038073dcd890bf5f66. Copyright (c) 2026 darshanseenivasakumar. MIT; see ./LICENSE. */
/** Glue words that stay small in the Ship wall, so content words carry the size. */
const SMALL = new Set([
    'a',
    'ah',
    'am',
    'an',
    'and',
    'are',
    'as',
    'at',
    'be',
    'but',
    'by',
    'da',
    'do',
    'for',
    'from',
    'he',
    'her',
    'his',
    'i',
    "i'd",
    "i'll",
    "i'm",
    "i've",
    'if',
    'im',
    'in',
    'is',
    'it',
    "it's",
    'its',
    'just',
    'la',
    'me',
    'my',
    'na',
    'of',
    'oh',
    'on',
    'ooh',
    'or',
    'our',
    'she',
    'so',
    'than',
    'that',
    'the',
    'their',
    'them',
    'then',
    'there',
    'they',
    'this',
    'to',
    'up',
    'us',
    'was',
    'we',
    'when',
    'with',
    'yeah',
    'you',
    "you're",
    'your',
]);

/** Helpers and short words: a step down, but still bold. */
const MEDIUM = new Set([
    'all',
    'been',
    'can',
    "can't",
    'cant',
    'could',
    "don't",
    'dont',
    'every',
    'get',
    'got',
    'had',
    'has',
    'have',
    'here',
    'how',
    'into',
    'know',
    'let',
    'like',
    'made',
    'make',
    'not',
    'now',
    'only',
    'onto',
    'over',
    'said',
    'say',
    'should',
    'some',
    'still',
    'too',
    'were',
    'what',
    'where',
    'who',
    'will',
    "won't",
    'wont',
    'would',
]);

/** Relative font size of a word in the Ship wall (0.5 small glue words … 1 content words). */
export function shipScale(word: string): number {
    const w = word.toLowerCase().replace(/’/g, "'");
    if (SMALL.has(w)) return 0.5;
    if (MEDIUM.has(w)) return 0.78;
    return [...w].length <= 2 ? 0.7 : 1;
}
